### ISSUE TITLE
Tooltips obscured by flash message

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#624] opened 2017-08-17 14:59 UTC
Given their interactive nature, tooltips should be higher in the z-index stack than the flash messages.

<img width="360" alt="screen_shot_2017-08-17_at_11 48 57_720" src="https://user-images.githubusercontent.com/18653/29418667-e66618a6-8364-11e7-8477-5633cdc8bc2a.png">

**Comment by nvasileiadis** [comment] 2017-08-22 13:47
No tooltips in CMS and the only dropdown menus that can co-exist with the flash messages have the right z-index and they appear alright.

**Comment by jamesjacobs** [comment] 2017-09-01 08:54
z-indexes is correct in Pulsar. The issue is down to dom order of the ribbon and the tooltip. Can be resolved by setting the container option on the tooltip to body `'data-container': 'body'.

![screen shot 2017-09-01 at 09 51 49](https://user-images.githubusercontent.com/756393/29962538-7b5eb82c-8efb-11e7-9ad6-71fb30969234.png)

**Closed by jamesjacobs** 2017-09-01 08:54 UTC
Labels: bug
